# Generated by Django 5.0 on 2025-07-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Matéria-Prima')),
                ('unidade_compra', models.CharField(choices=[('m²', 'Metro Quadrado (m²)'), ('un', 'Unidade (un)'), ('kg', 'Quilograma (kg)'), ('L', 'Litro (L)'), ('m', 'Metro Linear (m)'), ('folha', 'Folha')], max_length=10, verbose_name='Unidade de Compra')),
                ('custo_unidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo por Unidade de Compra')),
            ],
            options={
                'verbose_name': 'Matéria-Prima',
                'verbose_name_plural': 'Matérias-Primas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='materias_primas',
            field=models.ManyToManyField(blank=True, related_name='fornecedores', to='suppliers.materiaprima', verbose_name='Matérias-Primas Fornecidas'),
        ),
    ]
